version: "2"
services:
  web:
    build:
      context: ./src
    container_name: tomcat_eager
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - URL_BASE
      - MYSQL_CONN_URL 
  
    links:
      - mysql_eager:mysql_eager
    ports: 
      - "9090:8080"
      - "443:8443"
      - "8443:8443"
    volumes:
      # Names within curly brackets '{}' are path variables and should be substituted by those that the user assigns
      - ./target/logspringmvc.war:/usr/tomcat/webapps/ROOT.war
      - myvol:/home/term
      - ./.ssh/id_rsa:/usr/tomcat/.ssh/PrivateKey.ppk
      - eager:/home/eager/users
      - ./keystore:/usr/tomcat/keystore
      - ./server.xml:/usr/tomcat/conf/server.xml



  mysql_eager:
    image: mysql
    container_name: mysql_eager
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_SERVER
    ports:
      - "6603:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - data:/var/lib/mysql


volumes:
  data:
    driver: local
  myvol:
    external: true
  eager:
    external: true
